<?php
/**
 * @file
 * Testing module.
 */

/**
 * Implements hook_rules_plugin_info().
 */
function rules_conditional_test_rules_plugin_info() {
  return array(
    'stub conditional' => array(
      'label' => 'Stub conditional',
      'class' => 'RulesConditionalTestStubContainer',
      'embeddable' => 'RulesActionContainer',
      'extenders' => array(
        'RulesPluginUIInterface' => array(
          'class' => 'RulesPluginUI',
        ),
      ),
    ),
    'stub conditional element' => array(
      'label' => 'Stub conditional element',
      'class' => 'RulesConditionalTestStubElement',
      'embeddable' => 'RulesConditionalTestStubContainer',
      'extenders' => array(
        'RulesPluginUIInterface' => array(
          'class' => 'RulesPluginUI',
        ),
      ),
    ),
    'stub conditional default element' => array(
      'label' => 'Stub conditional default element',
      'class' => 'RulesConditionalTestStubDefaultElement',
      'embeddable' => 'RulesConditionalTestStubContainer',
      'extenders' => array(
        'RulesPluginUIInterface' => array(
          'class' => 'RulesPluginUI',
        ),
      ),
    ),
  );
}
